//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_Managment_System_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContactsEntities : DbContext
    {
        public ContactsEntities()
            : base("name=ContactsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
    
        public virtual int MigrateContactDataFinal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MigrateContactDataFinal");
        }
    }
}
