//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_Managment_System_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int Date_id { get; set; }
        public int Contact_id { get; set; }
        public string Date_type { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
    }
}
